content_paths:
- /home/runner/work/BartoszOsiej.github.io/BartoszOsiej.github.io/content
default_profile: everything
exclude_patterns:
- _drafts/*
- bip-calendar.md
file_extensions:
- .md
platforms:
  mastodon:
    api_key: mastodon.social:J867hvxj5Vw-5d15oIV07V7Nkbu1CRlDhLnCjXvPJO4
  medium:
    api_key: import
  twitter:
    api_key: manual
profiles:
  blogs:
  - devto
  - hashnode
  channels:
  - telegram
  - discord
  everything:
  - blogs
  - social
  - channels
  - linkedin
  - threads
  social:
  - bluesky
  - mastodon
site_base_url: https://bartoszosiej.github.io
site_root: /home/runner/work/BartoszOsiej.github.io/BartoszOsiej.github.io
