#!/usr/bin/env python3
"""Daily build-in-public draft generator (used by .github/workflows/bip-draft.yml).

Picks section N (day-of-year % N_DAYS) from content/bip-calendar.md,
best-effort enriches it with yesterday's public commits, then creates or
updates a single rolling issue labelled `bip-draft`.

Zero third-party dependencies: stdlib + GitHub REST via urllib.
"""
import datetime
import json
import os
import re
import urllib.request

REPO = os.environ.get("GITHUB_REPOSITORY", "BartoszOsiej/BartoszOsiej.github.io")
TOKEN = os.environ.get("GH_TOKEN")
LABEL = "bip-draft"
CALENDAR = "content/bip-calendar.md"
API = "https://api.github.com"


def api(url, method="GET", payload=None):
    req = urllib.request.Request(url, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "bip-draft-bot")
    if TOKEN:
        req.add_header("Authorization", f"Bearer {TOKEN}")
    data = None
    if payload is not None:
        data = json.dumps(payload).encode()
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, data=data, timeout=30) as r:
        body = r.read()
        return json.loads(body) if body else {}


def pick_day_section():
    with open(CALENDAR, encoding="utf-8") as f:
        text = f.read()
    sections = re.split(r"\n(?=## Day \d+)", text)
    sections = [s for s in sections if s.startswith("## Day ")]
    if not sections:
        raise SystemExit("no '## Day N' sections found in " + CALENDAR)
    n = datetime.date.today().timetuple().tm_yday % len(sections)
    return sections[n]


def yesterday_commits(limit=6):
    """Best-effort: public commits authored yesterday across the user's repos."""
    since = (datetime.date.today() - datetime.timedelta(days=1)).isoformat()
    try:
        commits = api(
            f"{API}/search/commits?q=author:BartoszOsiej+author-date:{since}&sort=author-date&order=desc&per_page={limit}"
        ).get("items", [])
        lines = []
        for c in commits:
            repo = c.get("repository", {}).get("full_name", "?")
            msg = (c.get("commit", {}).get("message") or "").splitlines()[0][:80]
            lines.append(f"- `{repo}`: {msg}")
        return lines
    except Exception as e:  # noqa: BLE001 — enrichment is optional
        print("commit enrichment skipped:", e)
        return []


def main():
    section = pick_day_section()
    lines = yesterday_commits()
    activity = (
        "\n### Yesterday's public commits (auto-collected)\n"
        + "\n".join(lines)
        if lines
        else "\n_(no public commits yesterday — lean on the prompt)_\n"
    )
    today = datetime.date.today().isoformat()
    body = (
        f"### Build-in-public draft — {today}\n\n"
        f"{section.strip()}\n\n{activity}\n\n---\n"
        "**Workflow:** edit this draft → post it (X/LinkedIn/Bluesky) **or** save it as "
        "`content/<slug>.md` and push — the cross-post workflow takes it from there.\n"
        "_Auto-generated by `bip-draft.yml`; this issue is rolled over daily._"
    )

    issues = api(f"{API}/repos/{REPO}/issues?labels={LABEL}&state=open&per_page=1")
    if issues:
        num = issues[0]["number"]
        api(f"{API}/repos/{REPO}/issues/{num}", method="PATCH",
            payload={"title": f"BIP draft — {today}", "body": body})
        print(f"updated rolling issue #{num}")
    else:
        created = api(f"{API}/repos/{REPO}/issues", method="POST", payload={
            "title": f"BIP draft — {today}",
            "body": body,
            "labels": [LABEL],
        })
        print(f"created issue #{created['number']}")


if __name__ == "__main__":
    main()
